version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "node-red"
        update-types: ["version-update:semver-major"]
      - dependency-name: "node-red-contrib-homekit-bridged"
        update-types: ["version-update:semver-major"]