name: Dependabot auto-merge

on:
  workflow_dispatch:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Bump versions
        uses: remorses/bump-version@js
        with:
          version_file: ./package.json
          github_token: ${{ secrets.GITHUB_TOKEN }}
       
